// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK6jZgZJ9FBBq2-ppKNwl_92FaGXG7l98',
    appId: '1:207946815471:web:23b51524132d01843c481a',
    messagingSenderId: '207946815471',
    projectId: 'joys-a4e34',
    authDomain: 'joys-a4e34.firebaseapp.com',
    storageBucket: 'joys-a4e34.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2fBoBCn-DTf-gjeloPAbyv74pHWLtB9A',
    appId: '1:207946815471:android:02f69e177cc548f43c481a',
    messagingSenderId: '207946815471',
    projectId: 'joys-a4e34',
    storageBucket: 'joys-a4e34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAll-YIgrGx8m2uIvLHMJTLl2UTZEs03bY',
    appId: '1:207946815471:ios:06aa458b9feee9853c481a',
    messagingSenderId: '207946815471',
    projectId: 'joys-a4e34',
    storageBucket: 'joys-a4e34.appspot.com',
    iosBundleId: 'com.example.assignmentjoyistick',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAll-YIgrGx8m2uIvLHMJTLl2UTZEs03bY',
    appId: '1:207946815471:ios:06aa458b9feee9853c481a',
    messagingSenderId: '207946815471',
    projectId: 'joys-a4e34',
    storageBucket: 'joys-a4e34.appspot.com',
    iosBundleId: 'com.example.assignmentjoyistick',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAK6jZgZJ9FBBq2-ppKNwl_92FaGXG7l98',
    appId: '1:207946815471:web:3b1a3d1060b658583c481a',
    messagingSenderId: '207946815471',
    projectId: 'joys-a4e34',
    authDomain: 'joys-a4e34.firebaseapp.com',
    storageBucket: 'joys-a4e34.appspot.com',
  );
}
